# Generated by Django 5.2.8 on 2026-01-14
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='图片标题')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图片描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '相册图片',
                'verbose_name_plural': '相册图片',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='宾客姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('invitation_code', models.CharField(max_length=50, unique=True, verbose_name='邀请码')),
                ('rsvp_status', models.BooleanField(default=False, verbose_name='是否确认出席')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='出席人数')),
                ('message', models.TextField(blank=True, verbose_name='祝福语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宾客',
                'verbose_name_plural': '宾客',
            },
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='婚礼标题')),
                ('bride_name', models.CharField(max_length=100, verbose_name='新娘姓名')),
                ('groom_name', models.CharField(max_length=100, verbose_name='新郎姓名')),
                ('event_date', models.DateTimeField(verbose_name='婚礼日期')),
                ('venue', models.CharField(max_length=300, verbose_name='婚礼地点')),
                ('address', models.TextField(verbose_name='详细地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='婚礼描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='wedding_covers/', verbose_name='封面图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '婚礼活动',
                'verbose_name_plural': '婚礼活动',
            },
        ),
    ]