# Generated by Django 5.2 on 2026-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, verbose_name='页面名称')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
                ('last_visited', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '页面访问统计',
                'verbose_name_plural': '页面访问统计',
                'unique_together': {('page_name',)},
            },
        ),
    ]
