# Generated by Django 5.2 on 2026-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_pagevisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'verbose_name': '页面访问统计'},
        ),
        migrations.AlterUniqueTogether(
            name='pagevisit',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='APIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('geocode', '地理编码'), ('reverse_geocode', '逆地理编码')], max_length=20, verbose_name='API类型')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('rate_limit_hit', models.BooleanField(default=False, verbose_name='达到速率限制')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API使用统计',
                'verbose_name_plural': 'API使用统计',
                'indexes': [models.Index(fields=['api_type', 'date'], name='invitation__api_typ_e9ab60_idx')],
                'unique_together': {('api_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='查询地址')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('result_data', models.JSONField(default=dict, verbose_name='地理编码结果数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '地理编码缓存',
                'verbose_name_plural': '地理编码缓存',
                'indexes': [models.Index(fields=['address'], name='invitation__address_be7f74_idx'), models.Index(fields=['expires_at'], name='invitation__expires_b7654f_idx')],
                'unique_together': {('address',)},
            },
        ),
    ]
