"""
Django settings for wedding_invitation project.

婚礼邀请函项目配置文件
此文件包含Django项目的所有配置设置，包括数据库、静态文件、日志等配置

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# 项目根目录路径
# 使用Path对象构建项目根目录路径，确保跨平台兼容性
# BASE_DIR指向项目根目录，即包含manage.py的目录
BASE_DIR = Path(__file__).resolve().parent.parent


# 开发环境快速启动设置 - 不适用于生产环境
# 生产环境部署前请参考: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 安全警告: 生产环境中请保持密钥安全!
# SECRET_KEY用于Django的加密签名，如会话、CSRF保护等
SECRET_KEY = 'django-insecure-4z2c^=%vd4l=(r-d&cvs%jcii+)x_+nc_f_6!68!zyyz&^)=s8'

# 安全警告: 生产环境中请勿开启调试模式!
# DEBUG=True将显示详细的错误页面，便于开发但存在安全风险
DEBUG = True

# 允许的主机列表
# 生产环境中应设置为允许访问此Django应用的主机名或IP地址
ALLOWED_HOSTS = []


# 应用程序定义
# INSTALLED_APPS包含项目中所有已安装的Django应用
INSTALLED_APPS = [
    'django.contrib.admin',      # Django管理后台
    'django.contrib.auth',       # 用户认证系统
    'django.contrib.contenttypes', # 内容类型框架
    'django.contrib.sessions',    # 会话框架
    'django.contrib.messages',    # 消息框架
    'django.contrib.staticfiles', # 静态文件处理
    'invitation',                # 自定义的婚礼邀请函应用
]

# 中间件配置
# 中间件是处理请求和响应的钩子，按顺序执行
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',        # 安全中间件
    'django.contrib.sessions.middleware.SessionMiddleware', # 会话中间件
    'django.middleware.common.CommonMiddleware',            # 通用中间件
    'django.middleware.csrf.CsrfViewMiddleware',           # CSRF保护
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 认证中间件
    'django.contrib.messages.middleware.MessageMiddleware', # 消息中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # 点击劫持保护
]

# 根URL配置模块
ROOT_URLCONF = 'wedding_invitation.urls'

# 模板配置
# 定义Django如何查找和渲染模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # 模板引擎
        'DIRS': [BASE_DIR / 'templates'],  # 全局模板目录
        'APP_DIRS': True,  # 允许在每个应用的templates子目录中查找模板
        'OPTIONS': {
            'context_processors': [  # 模板上下文处理器
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI应用程序配置
WSGI_APPLICATION = 'wedding_invitation.wsgi.application'


# 数据库配置
# 参考: https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 使用SQLite数据库引擎
        'NAME': BASE_DIR / 'db.sqlite3',        # 数据库文件路径
    }
}


# 密码验证配置
# 参考: https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 国际化配置
# 参考: https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'  # 使用简体中文

TIME_ZONE = 'Asia/Shanghai'  # 设置时区为上海时区

USE_I18N = True  # 启用国际化翻译
USE_L10N = True  # 启用本地化格式
USE_TZ = True    # 启用时区支持


# 静态文件配置 (CSS, JavaScript, Images)
# 参考: https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'  # 静态文件URL前缀

# 静态文件目录列表
# Django会在这些目录中查找静态文件
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 媒体文件配置
# 媒体文件是用户上传的文件，如图片、文档等
MEDIA_URL = '/media/'  # 媒体文件URL前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 媒体文件存储根目录

# 相册图片配置
# 定义相册图片和婚礼封面上传路径
GALLERY_UPLOAD_PATH = 'gallery/'  # 相册图片存储路径
WEDDING_COVERS_UPLOAD_PATH = 'wedding_covers/'  # 婚礼封面图片存储路径

# 高德地图Web服务API密钥
# 用于后端地理编码和逆地理编码功能
import os
AMAP_WEB_SERVICE_KEY = os.environ.get('AMAP_WEB_SERVICE_KEY', os.environ.get('AMAP_API_KEY', 'fc00ede691f6498051e4fa629bc095e0'))  # 优先使用专用的Web服务密钥，如果不存在则使用通用密钥，最后使用默认值

# 高德地图JavaScript API密钥
# 用于前端地图展示功能
AMAP_JS_API_KEY = os.environ.get('AMAP_JS_API_KEY', os.environ.get('AMAP_API_KEY', '4cc299e7b9e737e16ee2fb6c0bfa7aeb'))  # 优先使用专用的JS API密钥，如果不存在则使用通用密钥，最后使用默认值

# 高德地图安全密钥（必需，用于JS API 2.0）
# 如果您的API Key没有安全密钥，可以留空或删除此配置
AMAP_SECURITY_JS_CODE = os.environ.get('AMAP_SECURITY_JS_CODE', 'cee092ed483cff75e5c15da84162fc65	')  # 从环境变量获取安全密钥，如果没有则留空

# 默认主键字段类型
# 参考: https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 日志配置
# 配置Django的日志系统，包括日志格式、处理器和记录器
LOGGING = {
    'version': 1,  # 日志配置版本号
    'disable_existing_loggers': False,  # 不禁用已存在的日志记录器

    # 日志格式化器定义
    'formatters': {
        'verbose': {  # 详细格式
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {  # 简单格式
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {  # 详细格式，包含函数名和行号
            'format': '{levelname} {asctime} {name} {module} {funcName}:{lineno} - {message}',
            'style': '{',
        },
    },

    # 日志处理器定义
    'handlers': {
        'console': {  # 控制台输出处理器
            'level': 'INFO',  # 处理INFO级别及以上日志
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',  # 使用详细格式
        },
        'file': {  # 文件处理器
            'level': 'INFO',  # 处理INFO级别及以上日志
            'class': 'logging.handlers.RotatingFileHandler',  # 使用轮转文件处理器
            'filename': BASE_DIR / 'logs' / 'django.log',  # 日志文件路径
            'maxBytes': 1024*1024*10,  # 最大文件大小: 10MB
            'backupCount': 5,  # 保留的备份文件数量
            'formatter': 'detailed',  # 使用详细格式
        },
        'db_file': {  # 数据库专用日志文件处理器
            'level': 'DEBUG',  # 处理DEBUG级别及以上日志
            'class': 'logging.handlers.RotatingFileHandler',  # 使用轮转文件处理器
            'filename': BASE_DIR / 'logs' / 'database.log',  # 数据库日志文件路径
            'maxBytes': 1024*1024*10,  # 最大文件大小: 10MB
            'backupCount': 5,  # 保留的备份文件数量
            'formatter': 'detailed',  # 使用详细格式
        },
    },

    # 根日志记录器配置
    'root': {
        'handlers': ['console', 'file'],  # 使用控制台和文件处理器
        'level': 'INFO',  # 记录INFO级别及以上日志
    },

    # 特定日志记录器配置
    'loggers': {
        'django': {  # Django框架日志
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # 不传播到父记录器
        },
        'django.db.backends': {  # 数据库后端日志
            'handlers': ['console', 'db_file'],
            'level': 'DEBUG',  # 开启数据库查询日志，便于调试
            'propagate': False,
        },
        'invitation': {  # 婚礼邀请函应用日志
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {  # Django请求日志
            'handlers': ['console', 'file'],
            'level': 'ERROR',  # 只记录错误级别的请求日志
            'propagate': False,
        },
    },
}
